### ISSUE TITLE
Creating a new application

### ISSUE THREAD

**Issue by batuhancengiz** [Ditectrev/Professional-Scrum-Developer-I-PSD-I-Exam-Dumps-Questions-Answers#33]
I've created new application to read your ReadMe.md file and convert to real exam application. Maybe you guys want to try it!

Just download the ExamGenerator_v1.0.0.zip and import md files to the application.

https://github.com/batuhancengiz/ExamGenerator/releases/tag/v1.0.0
https://github.com/batuhancengiz/ExamGenerator/releases/download/v1.0.0/ExamGenerator_v1.0.0.zip

**Comment by danieldanielecki** [comment]
@batuhancengiz can you please share some screenshots / video in that repository how it works?

**Comment by danieldanielecki** [comment]
> ![image](https://private-user-images.githubusercontent.com/82826094/353183448-2a426e59-9f82-4b74-bd44-7c3d1e094272.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMzMyMzAsIm5iZiI6MTcyMjMzMjkzMCwicGF0aCI6Ii84MjgyNjA5NC8zNTMxODM0NDgtMmE0MjZlNTktOWY4Mi00Yjc0LWJkNDQtN2MzZDFlMDk0MjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA5NDg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1OTdhYWYzZjQ3YTVjM2FmYTUzZmYxMDMzYmUzNjJiNDVkMTk5ZWQ3ZmE5MDBhODAzNTZhYmU1NmVjOWIwNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9g-a0FD3gkH1qJGLYj2m9IcEQRyJzQlHcleFUyIO1Tw)
> 
> Import directly readmd file and you can select right option or options in window and also you can check your answers are correct or not.

Is it a Windows application? If I see correctly, that's C#.
Does it has a potential to leverage https://platform.uno?

We've already published our other students projects (iOS: https://apps.apple.com/app/cloudmaster-swift/id6503601139 & Web: https://education.ditectrev.com), so we can try the same here, but I need more information.

Have you joined our Discord https://discord.gg/RFjtXKfJy3?

**Comment by danieldanielecki** [comment]
@batuhancengiz anything to add?
